language: node_js
node_js:
  - 0.8
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
  firefox: "24.0"
branches:
  except:
    - gh-pages
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'Installing SlimerJS'"
  - "wget http://download.slimerjs.org/v0.8/slimerjs-0.8.3.zip"
  - "unzip slimerjs-0.8.3.zip"
  - "mv slimerjs-0.8.3 ./slimerjs"
  - "echo 'Installing Grunt'"
  - "npm install -g grunt-cli"
